name = "botrun24-721"  # Name of your Worker
type = "javascript"  # Type of Worker (usually javascript for Node.js)

account_id = "a949517f80d6d344b57803803f8aa993"
workers_dev = true
compatibility_flags = []

# Define the route (optional, if deploying on a custom route)
# route = "example.com/*"
# zone_id = "YOUR_ZONE_ID"
